env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: detect
ignorePatterns:
  - "*.js"
rules:
  eqeqeq: "off"
  camelcase: "off"
  no-console: "off"
  no-shadow: "off"
  semi:
    - error
    - never
  import/no-anonymous-default-export: "off"
  "react/display-name": "off"
  "react/react-in-jsx-scope": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "off"
